version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - errcheck
    - errorlint
    - exhaustive
    - ginkgolinter
    - goconst
    - gocritic
    - godot
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    dupl:
      threshold: 200
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
        - importShadow
        - unnamedResult
        - unnecessaryBlock
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      settings:
        hugeParam:
          sizeThreshold: 512
        rangeValCopy:
          sizeThreshold: 512
    gocyclo:
      min-complexity: 16
    goheader:
      template-path: ./hack/boilerplate.go.txt
    lll:
      line-length: 300
    misspell:
      locale: US
    revive:
      rules:
        - name: comment-spacings
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - gocyclo
          - gosec
          - lll
          - unparam
        path: _test(ing)?\.go
      - linters:
          - gocritic
        path: _test\.go
        text: (unnamedResult|exitAfterDefer)
      - linters:
          - gosec
        text: 'G101:'
      - linters:
          - goheader
        text: 'Actual:'
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - prefix("github.com/konpyutaika/nifikop")
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - cmd/main.go
      - cmd/kubectl-nifikop/main.go
      - internal/controller/suite_test.go
