//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v2alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterReference) DeepCopyInto(out *ClusterReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterReference.
func (in *ClusterReference) DeepCopy() *ClusterReference {
	if in == nil {
		return nil
	}
	out := new(ClusterReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitHubConfig) DeepCopyInto(out *GitHubConfig) {
	*out = *in
	if in.ApiUrl != nil {
		in, out := &in.ApiUrl, &out.ApiUrl
		*out = new(string)
		**out = **in
	}
	if in.AuthenticationType != nil {
		in, out := &in.AuthenticationType, &out.AuthenticationType
		*out = new(GitHubAuthenticationType)
		**out = **in
	}
	if in.PersonalAccessTokenSecretRef != nil {
		in, out := &in.PersonalAccessTokenSecretRef, &out.PersonalAccessTokenSecretRef
		*out = new(SecretConfigReference)
		**out = **in
	}
	if in.AppId != nil {
		in, out := &in.AppId, &out.AppId
		*out = new(string)
		**out = **in
	}
	if in.AppPrivateKeySecretRef != nil {
		in, out := &in.AppPrivateKeySecretRef, &out.AppPrivateKeySecretRef
		*out = new(SecretConfigReference)
		**out = **in
	}
	if in.DefaultBranch != nil {
		in, out := &in.DefaultBranch, &out.DefaultBranch
		*out = new(string)
		**out = **in
	}
	if in.RepositoryPath != nil {
		in, out := &in.RepositoryPath, &out.RepositoryPath
		*out = new(string)
		**out = **in
	}
	if in.DirectoryFilterExclusion != nil {
		in, out := &in.DirectoryFilterExclusion, &out.DirectoryFilterExclusion
		*out = new(string)
		**out = **in
	}
	if in.ParameterContextValues != nil {
		in, out := &in.ParameterContextValues, &out.ParameterContextValues
		*out = new(RegistryClientParameterContextValues)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitHubConfig.
func (in *GitHubConfig) DeepCopy() *GitHubConfig {
	if in == nil {
		return nil
	}
	out := new(GitHubConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitLabConfig) DeepCopyInto(out *GitLabConfig) {
	*out = *in
	if in.Url != nil {
		in, out := &in.Url, &out.Url
		*out = new(string)
		**out = **in
	}
	if in.ApiVersion != nil {
		in, out := &in.ApiVersion, &out.ApiVersion
		*out = new(GitLabApiVersion)
		**out = **in
	}
	if in.AuthenticationType != nil {
		in, out := &in.AuthenticationType, &out.AuthenticationType
		*out = new(GitLabAuthenticationType)
		**out = **in
	}
	if in.AccessTokenSecretRef != nil {
		in, out := &in.AccessTokenSecretRef, &out.AccessTokenSecretRef
		*out = new(SecretConfigReference)
		**out = **in
	}
	if in.ConnectTimeout != nil {
		in, out := &in.ConnectTimeout, &out.ConnectTimeout
		*out = new(string)
		**out = **in
	}
	if in.ReadTimeout != nil {
		in, out := &in.ReadTimeout, &out.ReadTimeout
		*out = new(string)
		**out = **in
	}
	if in.DefaultBranch != nil {
		in, out := &in.DefaultBranch, &out.DefaultBranch
		*out = new(string)
		**out = **in
	}
	if in.RepositoryPath != nil {
		in, out := &in.RepositoryPath, &out.RepositoryPath
		*out = new(string)
		**out = **in
	}
	if in.DirectoryFilterExclusion != nil {
		in, out := &in.DirectoryFilterExclusion, &out.DirectoryFilterExclusion
		*out = new(string)
		**out = **in
	}
	if in.ParameterContextValues != nil {
		in, out := &in.ParameterContextValues, &out.ParameterContextValues
		*out = new(RegistryClientParameterContextValues)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitLabConfig.
func (in *GitLabConfig) DeepCopy() *GitLabConfig {
	if in == nil {
		return nil
	}
	out := new(GitLabConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NifiRegistryClient) DeepCopyInto(out *NifiRegistryClient) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NifiRegistryClient.
func (in *NifiRegistryClient) DeepCopy() *NifiRegistryClient {
	if in == nil {
		return nil
	}
	out := new(NifiRegistryClient)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NifiRegistryClient) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NifiRegistryClientList) DeepCopyInto(out *NifiRegistryClientList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NifiRegistryClient, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NifiRegistryClientList.
func (in *NifiRegistryClientList) DeepCopy() *NifiRegistryClientList {
	if in == nil {
		return nil
	}
	out := new(NifiRegistryClientList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NifiRegistryClientList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NifiRegistryClientSpec) DeepCopyInto(out *NifiRegistryClientSpec) {
	*out = *in
	out.ClusterRef = in.ClusterRef
	if in.RegistryClientConfig != nil {
		in, out := &in.RegistryClientConfig, &out.RegistryClientConfig
		*out = new(RegistryClientConfig)
		**out = **in
	}
	if in.GitHubConfig != nil {
		in, out := &in.GitHubConfig, &out.GitHubConfig
		*out = new(GitHubConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.GitLabConfig != nil {
		in, out := &in.GitLabConfig, &out.GitLabConfig
		*out = new(GitLabConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NifiRegistryClientSpec.
func (in *NifiRegistryClientSpec) DeepCopy() *NifiRegistryClientSpec {
	if in == nil {
		return nil
	}
	out := new(NifiRegistryClientSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NifiRegistryClientStatus) DeepCopyInto(out *NifiRegistryClientStatus) {
	*out = *in
	if in.LatestSecretsResourceVersion != nil {
		in, out := &in.LatestSecretsResourceVersion, &out.LatestSecretsResourceVersion
		*out = make([]SecretResourceVersion, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NifiRegistryClientStatus.
func (in *NifiRegistryClientStatus) DeepCopy() *NifiRegistryClientStatus {
	if in == nil {
		return nil
	}
	out := new(NifiRegistryClientStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryClientConfig) DeepCopyInto(out *RegistryClientConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryClientConfig.
func (in *RegistryClientConfig) DeepCopy() *RegistryClientConfig {
	if in == nil {
		return nil
	}
	out := new(RegistryClientConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretConfigReference) DeepCopyInto(out *SecretConfigReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretConfigReference.
func (in *SecretConfigReference) DeepCopy() *SecretConfigReference {
	if in == nil {
		return nil
	}
	out := new(SecretConfigReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretResourceVersion) DeepCopyInto(out *SecretResourceVersion) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretResourceVersion.
func (in *SecretResourceVersion) DeepCopy() *SecretResourceVersion {
	if in == nil {
		return nil
	}
	out := new(SecretResourceVersion)
	in.DeepCopyInto(out)
	return out
}
