//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2020.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "github.com/cert-manager/cert-manager/pkg/apis/meta/v1"
	corev1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessPolicy) DeepCopyInto(out *AccessPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessPolicy.
func (in *AccessPolicy) DeepCopy() *AccessPolicy {
	if in == nil {
		return nil
	}
	out := new(AccessPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizerConfig) DeepCopyInto(out *AuthorizerConfig) {
	*out = *in
	if in.ReplaceTemplateConfigMap != nil {
		in, out := &in.ReplaceTemplateConfigMap, &out.ReplaceTemplateConfigMap
		*out = new(ConfigmapReference)
		**out = **in
	}
	if in.ReplaceTemplateSecretConfig != nil {
		in, out := &in.ReplaceTemplateSecretConfig, &out.ReplaceTemplateSecretConfig
		*out = new(SecretConfigReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizerConfig.
func (in *AuthorizerConfig) DeepCopy() *AuthorizerConfig {
	if in == nil {
		return nil
	}
	out := new(AuthorizerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapNotificationServicesConfig) DeepCopyInto(out *BootstrapNotificationServicesConfig) {
	*out = *in
	if in.ReplaceConfigMap != nil {
		in, out := &in.ReplaceConfigMap, &out.ReplaceConfigMap
		*out = new(ConfigmapReference)
		**out = **in
	}
	if in.ReplaceSecretConfig != nil {
		in, out := &in.ReplaceSecretConfig, &out.ReplaceSecretConfig
		*out = new(SecretConfigReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapNotificationServicesConfig.
func (in *BootstrapNotificationServicesConfig) DeepCopy() *BootstrapNotificationServicesConfig {
	if in == nil {
		return nil
	}
	out := new(BootstrapNotificationServicesConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapProperties) DeepCopyInto(out *BootstrapProperties) {
	*out = *in
	if in.OverrideConfigMap != nil {
		in, out := &in.OverrideConfigMap, &out.OverrideConfigMap
		*out = new(ConfigmapReference)
		**out = **in
	}
	if in.OverrideSecretConfig != nil {
		in, out := &in.OverrideSecretConfig, &out.OverrideSecretConfig
		*out = new(SecretConfigReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapProperties.
func (in *BootstrapProperties) DeepCopy() *BootstrapProperties {
	if in == nil {
		return nil
	}
	out := new(BootstrapProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterReference) DeepCopyInto(out *ClusterReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterReference.
func (in *ClusterReference) DeepCopy() *ClusterReference {
	if in == nil {
		return nil
	}
	out := new(ClusterReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigmapReference) DeepCopyInto(out *ConfigmapReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigmapReference.
func (in *ConfigmapReference) DeepCopy() *ConfigmapReference {
	if in == nil {
		return nil
	}
	out := new(ConfigmapReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisruptionBudget) DeepCopyInto(out *DisruptionBudget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisruptionBudget.
func (in *DisruptionBudget) DeepCopy() *DisruptionBudget {
	if in == nil {
		return nil
	}
	out := new(DisruptionBudget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DropRequest) DeepCopyInto(out *DropRequest) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DropRequest.
func (in *DropRequest) DeepCopy() *DropRequest {
	if in == nil {
		return nil
	}
	out := new(DropRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalServiceConfig) DeepCopyInto(out *ExternalServiceConfig) {
	*out = *in
	in.Metadata.DeepCopyInto(&out.Metadata)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalServiceConfig.
func (in *ExternalServiceConfig) DeepCopy() *ExternalServiceConfig {
	if in == nil {
		return nil
	}
	out := new(ExternalServiceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalServiceSpec) DeepCopyInto(out *ExternalServiceSpec) {
	*out = *in
	if in.PortConfigs != nil {
		in, out := &in.PortConfigs, &out.PortConfigs
		*out = make([]PortConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExternalIPs != nil {
		in, out := &in.ExternalIPs, &out.ExternalIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LoadBalancerSourceRanges != nil {
		in, out := &in.LoadBalancerSourceRanges, &out.LoadBalancerSourceRanges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LoadBalancerClass != nil {
		in, out := &in.LoadBalancerClass, &out.LoadBalancerClass
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalServiceSpec.
func (in *ExternalServiceSpec) DeepCopy() *ExternalServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ExternalServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowPosition) DeepCopyInto(out *FlowPosition) {
	*out = *in
	if in.X != nil {
		in, out := &in.X, &out.X
		*out = new(int64)
		**out = **in
	}
	if in.Y != nil {
		in, out := &in.Y, &out.Y
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowPosition.
func (in *FlowPosition) DeepCopy() *FlowPosition {
	if in == nil {
		return nil
	}
	out := new(FlowPosition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GracefulActionState) DeepCopyInto(out *GracefulActionState) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GracefulActionState.
func (in *GracefulActionState) DeepCopy() *GracefulActionState {
	if in == nil {
		return nil
	}
	out := new(GracefulActionState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InternalListenerConfig) DeepCopyInto(out *InternalListenerConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InternalListenerConfig.
func (in *InternalListenerConfig) DeepCopy() *InternalListenerConfig {
	if in == nil {
		return nil
	}
	out := new(InternalListenerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LdapConfiguration) DeepCopyInto(out *LdapConfiguration) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LdapConfiguration.
func (in *LdapConfiguration) DeepCopy() *LdapConfiguration {
	if in == nil {
		return nil
	}
	out := new(LdapConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListenersConfig) DeepCopyInto(out *ListenersConfig) {
	*out = *in
	if in.InternalListeners != nil {
		in, out := &in.InternalListeners, &out.InternalListeners
		*out = make([]InternalListenerConfig, len(*in))
		copy(*out, *in)
	}
	if in.SSLSecrets != nil {
		in, out := &in.SSLSecrets, &out.SSLSecrets
		*out = new(SSLSecrets)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListenersConfig.
func (in *ListenersConfig) DeepCopy() *ListenersConfig {
	if in == nil {
		return nil
	}
	out := new(ListenersConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogbackConfig) DeepCopyInto(out *LogbackConfig) {
	*out = *in
	if in.ReplaceConfigMap != nil {
		in, out := &in.ReplaceConfigMap, &out.ReplaceConfigMap
		*out = new(ConfigmapReference)
		**out = **in
	}
	if in.ReplaceSecretConfig != nil {
		in, out := &in.ReplaceSecretConfig, &out.ReplaceSecretConfig
		*out = new(SecretConfigReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogbackConfig.
func (in *LogbackConfig) DeepCopy() *LogbackConfig {
	if in == nil {
		return nil
	}
	out := new(LogbackConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedUser) DeepCopyInto(out *ManagedUser) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedUser.
func (in *ManagedUser) DeepCopy() *ManagedUser {
	if in == nil {
		return nil
	}
	out := new(ManagedUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Metadata) DeepCopyInto(out *Metadata) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Metadata.
func (in *Metadata) DeepCopy() *Metadata {
	if in == nil {
		return nil
	}
	out := new(Metadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NifiCluster) DeepCopyInto(out *NifiCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NifiCluster.
func (in *NifiCluster) DeepCopy() *NifiCluster {
	if in == nil {
		return nil
	}
	out := new(NifiCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NifiCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NifiClusterList) DeepCopyInto(out *NifiClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NifiCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NifiClusterList.
func (in *NifiClusterList) DeepCopy() *NifiClusterList {
	if in == nil {
		return nil
	}
	out := new(NifiClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NifiClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NifiClusterSpec) DeepCopyInto(out *NifiClusterSpec) {
	*out = *in
	out.SecretRef = in.SecretRef
	in.Service.DeepCopyInto(&out.Service)
	in.Pod.DeepCopyInto(&out.Pod)
	if in.InitContainers != nil {
		in, out := &in.InitContainers, &out.InitContainers
		*out = make([]corev1.Container, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ManagedAdminUsers != nil {
		in, out := &in.ManagedAdminUsers, &out.ManagedAdminUsers
		*out = make([]ManagedUser, len(*in))
		copy(*out, *in)
	}
	if in.ManagedReaderUsers != nil {
		in, out := &in.ManagedReaderUsers, &out.ManagedReaderUsers
		*out = make([]ManagedUser, len(*in))
		copy(*out, *in)
	}
	in.ReadOnlyConfig.DeepCopyInto(&out.ReadOnlyConfig)
	if in.NodeConfigGroups != nil {
		in, out := &in.NodeConfigGroups, &out.NodeConfigGroups
		*out = make(map[string]NodeConfig, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.NodeUserIdentityTemplate != nil {
		in, out := &in.NodeUserIdentityTemplate, &out.NodeUserIdentityTemplate
		*out = new(string)
		**out = **in
	}
	if in.Nodes != nil {
		in, out := &in.Nodes, &out.Nodes
		*out = make([]Node, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.DisruptionBudget = in.DisruptionBudget
	out.LdapConfiguration = in.LdapConfiguration
	out.NifiClusterTaskSpec = in.NifiClusterTaskSpec
	if in.ListenersConfig != nil {
		in, out := &in.ListenersConfig, &out.ListenersConfig
		*out = new(ListenersConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SidecarConfigs != nil {
		in, out := &in.SidecarConfigs, &out.SidecarConfigs
		*out = make([]corev1.Container, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExternalServices != nil {
		in, out := &in.ExternalServices, &out.ExternalServices
		*out = make([]ExternalServiceConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TopologySpreadConstraints != nil {
		in, out := &in.TopologySpreadConstraints, &out.TopologySpreadConstraints
		*out = make([]corev1.TopologySpreadConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NifiControllerTemplate != nil {
		in, out := &in.NifiControllerTemplate, &out.NifiControllerTemplate
		*out = new(string)
		**out = **in
	}
	if in.ControllerUserIdentity != nil {
		in, out := &in.ControllerUserIdentity, &out.ControllerUserIdentity
		*out = new(string)
		**out = **in
	}
	in.SingleUserConfiguration.DeepCopyInto(&out.SingleUserConfiguration)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NifiClusterSpec.
func (in *NifiClusterSpec) DeepCopy() *NifiClusterSpec {
	if in == nil {
		return nil
	}
	out := new(NifiClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NifiClusterStatus) DeepCopyInto(out *NifiClusterStatus) {
	*out = *in
	if in.NodesState != nil {
		in, out := &in.NodesState, &out.NodesState
		*out = make(map[string]NodeState, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	out.RollingUpgrade = in.RollingUpgrade
	out.PrometheusReportingTask = in.PrometheusReportingTask
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NifiClusterStatus.
func (in *NifiClusterStatus) DeepCopy() *NifiClusterStatus {
	if in == nil {
		return nil
	}
	out := new(NifiClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NifiClusterTaskSpec) DeepCopyInto(out *NifiClusterTaskSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NifiClusterTaskSpec.
func (in *NifiClusterTaskSpec) DeepCopy() *NifiClusterTaskSpec {
	if in == nil {
		return nil
	}
	out := new(NifiClusterTaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NifiDataflow) DeepCopyInto(out *NifiDataflow) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NifiDataflow.
func (in *NifiDataflow) DeepCopy() *NifiDataflow {
	if in == nil {
		return nil
	}
	out := new(NifiDataflow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NifiDataflow) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NifiDataflowList) DeepCopyInto(out *NifiDataflowList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NifiDataflow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NifiDataflowList.
func (in *NifiDataflowList) DeepCopy() *NifiDataflowList {
	if in == nil {
		return nil
	}
	out := new(NifiDataflowList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NifiDataflowList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NifiDataflowSpec) DeepCopyInto(out *NifiDataflowSpec) {
	*out = *in
	if in.FlowVersion != nil {
		in, out := &in.FlowVersion, &out.FlowVersion
		*out = new(int32)
		**out = **in
	}
	if in.FlowPosition != nil {
		in, out := &in.FlowPosition, &out.FlowPosition
		*out = new(FlowPosition)
		(*in).DeepCopyInto(*out)
	}
	if in.ParameterContextRef != nil {
		in, out := &in.ParameterContextRef, &out.ParameterContextRef
		*out = new(ParameterContextReference)
		**out = **in
	}
	if in.SyncMode != nil {
		in, out := &in.SyncMode, &out.SyncMode
		*out = new(DataflowSyncMode)
		**out = **in
	}
	out.ClusterRef = in.ClusterRef
	if in.RegistryClientRef != nil {
		in, out := &in.RegistryClientRef, &out.RegistryClientRef
		*out = new(RegistryClientReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NifiDataflowSpec.
func (in *NifiDataflowSpec) DeepCopy() *NifiDataflowSpec {
	if in == nil {
		return nil
	}
	out := new(NifiDataflowSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NifiDataflowStatus) DeepCopyInto(out *NifiDataflowStatus) {
	*out = *in
	if in.LatestUpdateRequest != nil {
		in, out := &in.LatestUpdateRequest, &out.LatestUpdateRequest
		*out = new(UpdateRequest)
		**out = **in
	}
	if in.LatestDropRequest != nil {
		in, out := &in.LatestDropRequest, &out.LatestDropRequest
		*out = new(DropRequest)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NifiDataflowStatus.
func (in *NifiDataflowStatus) DeepCopy() *NifiDataflowStatus {
	if in == nil {
		return nil
	}
	out := new(NifiDataflowStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NifiParameterContext) DeepCopyInto(out *NifiParameterContext) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NifiParameterContext.
func (in *NifiParameterContext) DeepCopy() *NifiParameterContext {
	if in == nil {
		return nil
	}
	out := new(NifiParameterContext)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NifiParameterContext) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NifiParameterContextList) DeepCopyInto(out *NifiParameterContextList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NifiParameterContext, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NifiParameterContextList.
func (in *NifiParameterContextList) DeepCopy() *NifiParameterContextList {
	if in == nil {
		return nil
	}
	out := new(NifiParameterContextList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NifiParameterContextList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NifiParameterContextSpec) DeepCopyInto(out *NifiParameterContextSpec) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make([]Parameter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.ClusterRef = in.ClusterRef
	if in.SecretRefs != nil {
		in, out := &in.SecretRefs, &out.SecretRefs
		*out = make([]SecretReference, len(*in))
		copy(*out, *in)
	}
	if in.InheritedParameterContexts != nil {
		in, out := &in.InheritedParameterContexts, &out.InheritedParameterContexts
		*out = make([]ParameterContextReference, len(*in))
		copy(*out, *in)
	}
	if in.DisableTakeOver != nil {
		in, out := &in.DisableTakeOver, &out.DisableTakeOver
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NifiParameterContextSpec.
func (in *NifiParameterContextSpec) DeepCopy() *NifiParameterContextSpec {
	if in == nil {
		return nil
	}
	out := new(NifiParameterContextSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NifiParameterContextStatus) DeepCopyInto(out *NifiParameterContextStatus) {
	*out = *in
	if in.LatestUpdateRequest != nil {
		in, out := &in.LatestUpdateRequest, &out.LatestUpdateRequest
		*out = new(ParameterContextUpdateRequest)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NifiParameterContextStatus.
func (in *NifiParameterContextStatus) DeepCopy() *NifiParameterContextStatus {
	if in == nil {
		return nil
	}
	out := new(NifiParameterContextStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NifiProperties) DeepCopyInto(out *NifiProperties) {
	*out = *in
	if in.OverrideConfigMap != nil {
		in, out := &in.OverrideConfigMap, &out.OverrideConfigMap
		*out = new(ConfigmapReference)
		**out = **in
	}
	if in.OverrideSecretConfig != nil {
		in, out := &in.OverrideSecretConfig, &out.OverrideSecretConfig
		*out = new(SecretConfigReference)
		**out = **in
	}
	if in.WebProxyHosts != nil {
		in, out := &in.WebProxyHosts, &out.WebProxyHosts
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NifiProperties.
func (in *NifiProperties) DeepCopy() *NifiProperties {
	if in == nil {
		return nil
	}
	out := new(NifiProperties)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NifiRegistryClient) DeepCopyInto(out *NifiRegistryClient) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NifiRegistryClient.
func (in *NifiRegistryClient) DeepCopy() *NifiRegistryClient {
	if in == nil {
		return nil
	}
	out := new(NifiRegistryClient)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NifiRegistryClient) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NifiRegistryClientList) DeepCopyInto(out *NifiRegistryClientList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NifiRegistryClient, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NifiRegistryClientList.
func (in *NifiRegistryClientList) DeepCopy() *NifiRegistryClientList {
	if in == nil {
		return nil
	}
	out := new(NifiRegistryClientList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NifiRegistryClientList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NifiRegistryClientSpec) DeepCopyInto(out *NifiRegistryClientSpec) {
	*out = *in
	out.ClusterRef = in.ClusterRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NifiRegistryClientSpec.
func (in *NifiRegistryClientSpec) DeepCopy() *NifiRegistryClientSpec {
	if in == nil {
		return nil
	}
	out := new(NifiRegistryClientSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NifiRegistryClientStatus) DeepCopyInto(out *NifiRegistryClientStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NifiRegistryClientStatus.
func (in *NifiRegistryClientStatus) DeepCopy() *NifiRegistryClientStatus {
	if in == nil {
		return nil
	}
	out := new(NifiRegistryClientStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NifiUser) DeepCopyInto(out *NifiUser) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NifiUser.
func (in *NifiUser) DeepCopy() *NifiUser {
	if in == nil {
		return nil
	}
	out := new(NifiUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NifiUser) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NifiUserGroup) DeepCopyInto(out *NifiUserGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NifiUserGroup.
func (in *NifiUserGroup) DeepCopy() *NifiUserGroup {
	if in == nil {
		return nil
	}
	out := new(NifiUserGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NifiUserGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NifiUserGroupList) DeepCopyInto(out *NifiUserGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NifiUserGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NifiUserGroupList.
func (in *NifiUserGroupList) DeepCopy() *NifiUserGroupList {
	if in == nil {
		return nil
	}
	out := new(NifiUserGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NifiUserGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NifiUserGroupSpec) DeepCopyInto(out *NifiUserGroupSpec) {
	*out = *in
	out.ClusterRef = in.ClusterRef
	if in.UsersRef != nil {
		in, out := &in.UsersRef, &out.UsersRef
		*out = make([]UserReference, len(*in))
		copy(*out, *in)
	}
	if in.AccessPolicies != nil {
		in, out := &in.AccessPolicies, &out.AccessPolicies
		*out = make([]AccessPolicy, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NifiUserGroupSpec.
func (in *NifiUserGroupSpec) DeepCopy() *NifiUserGroupSpec {
	if in == nil {
		return nil
	}
	out := new(NifiUserGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NifiUserGroupStatus) DeepCopyInto(out *NifiUserGroupStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NifiUserGroupStatus.
func (in *NifiUserGroupStatus) DeepCopy() *NifiUserGroupStatus {
	if in == nil {
		return nil
	}
	out := new(NifiUserGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NifiUserList) DeepCopyInto(out *NifiUserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NifiUser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NifiUserList.
func (in *NifiUserList) DeepCopy() *NifiUserList {
	if in == nil {
		return nil
	}
	out := new(NifiUserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NifiUserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NifiUserSpec) DeepCopyInto(out *NifiUserSpec) {
	*out = *in
	out.ClusterRef = in.ClusterRef
	if in.DNSNames != nil {
		in, out := &in.DNSNames, &out.DNSNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CreateCert != nil {
		in, out := &in.CreateCert, &out.CreateCert
		*out = new(bool)
		**out = **in
	}
	if in.AccessPolicies != nil {
		in, out := &in.AccessPolicies, &out.AccessPolicies
		*out = make([]AccessPolicy, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NifiUserSpec.
func (in *NifiUserSpec) DeepCopy() *NifiUserSpec {
	if in == nil {
		return nil
	}
	out := new(NifiUserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NifiUserStatus) DeepCopyInto(out *NifiUserStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NifiUserStatus.
func (in *NifiUserStatus) DeepCopy() *NifiUserStatus {
	if in == nil {
		return nil
	}
	out := new(NifiUserStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Node) DeepCopyInto(out *Node) {
	*out = *in
	if in.ReadOnlyConfig != nil {
		in, out := &in.ReadOnlyConfig, &out.ReadOnlyConfig
		*out = new(ReadOnlyConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeConfig != nil {
		in, out := &in.NodeConfig, &out.NodeConfig
		*out = new(NodeConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Node.
func (in *Node) DeepCopy() *Node {
	if in == nil {
		return nil
	}
	out := new(Node)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeConfig) DeepCopyInto(out *NodeConfig) {
	*out = *in
	if in.RunAsUser != nil {
		in, out := &in.RunAsUser, &out.RunAsUser
		*out = new(int64)
		**out = **in
	}
	if in.FSGroup != nil {
		in, out := &in.FSGroup, &out.FSGroup
		*out = new(int64)
		**out = **in
	}
	if in.IsNode != nil {
		in, out := &in.IsNode, &out.IsNode
		*out = new(bool)
		**out = **in
	}
	if in.NodeAffinity != nil {
		in, out := &in.NodeAffinity, &out.NodeAffinity
		*out = new(corev1.NodeAffinity)
		(*in).DeepCopyInto(*out)
	}
	if in.StorageConfigs != nil {
		in, out := &in.StorageConfigs, &out.StorageConfigs
		*out = make([]StorageConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExternalVolumeConfigs != nil {
		in, out := &in.ExternalVolumeConfigs, &out.ExternalVolumeConfigs
		*out = make([]VolumeConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ResourcesRequirements != nil {
		in, out := &in.ResourcesRequirements, &out.ResourcesRequirements
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]corev1.LocalObjectReference, len(*in))
		copy(*out, *in)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.PodMetadata.DeepCopyInto(&out.PodMetadata)
	if in.HostAliases != nil {
		in, out := &in.HostAliases, &out.HostAliases
		*out = make([]corev1.HostAlias, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PriorityClassName != nil {
		in, out := &in.PriorityClassName, &out.PriorityClassName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeConfig.
func (in *NodeConfig) DeepCopy() *NodeConfig {
	if in == nil {
		return nil
	}
	out := new(NodeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeState) DeepCopyInto(out *NodeState) {
	*out = *in
	out.GracefulActionState = in.GracefulActionState
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = (*in).DeepCopy()
	}
	in.LastUpdatedTime.DeepCopyInto(&out.LastUpdatedTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeState.
func (in *NodeState) DeepCopy() *NodeState {
	if in == nil {
		return nil
	}
	out := new(NodeState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Pair) DeepCopyInto(out *Pair) {
	*out = *in
	in.Value.DeepCopyInto(&out.Value)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Pair.
func (in *Pair) DeepCopy() *Pair {
	if in == nil {
		return nil
	}
	out := new(Pair)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in PairList) DeepCopyInto(out *PairList) {
	{
		in := &in
		*out = make(PairList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PairList.
func (in PairList) DeepCopy() PairList {
	if in == nil {
		return nil
	}
	out := new(PairList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Parameter) DeepCopyInto(out *Parameter) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Parameter.
func (in *Parameter) DeepCopy() *Parameter {
	if in == nil {
		return nil
	}
	out := new(Parameter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParameterContextReference) DeepCopyInto(out *ParameterContextReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParameterContextReference.
func (in *ParameterContextReference) DeepCopy() *ParameterContextReference {
	if in == nil {
		return nil
	}
	out := new(ParameterContextReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParameterContextUpdateRequest) DeepCopyInto(out *ParameterContextUpdateRequest) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParameterContextUpdateRequest.
func (in *ParameterContextUpdateRequest) DeepCopy() *ParameterContextUpdateRequest {
	if in == nil {
		return nil
	}
	out := new(ParameterContextUpdateRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodPolicy) DeepCopyInto(out *PodPolicy) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.HostAliases != nil {
		in, out := &in.HostAliases, &out.HostAliases
		*out = make([]corev1.HostAlias, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ReadinessProbe != nil {
		in, out := &in.ReadinessProbe, &out.ReadinessProbe
		*out = new(corev1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.LivenessProbe != nil {
		in, out := &in.LivenessProbe, &out.LivenessProbe
		*out = new(corev1.Probe)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodPolicy.
func (in *PodPolicy) DeepCopy() *PodPolicy {
	if in == nil {
		return nil
	}
	out := new(PodPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortConfig) DeepCopyInto(out *PortConfig) {
	*out = *in
	if in.NodePort != nil {
		in, out := &in.NodePort, &out.NodePort
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortConfig.
func (in *PortConfig) DeepCopy() *PortConfig {
	if in == nil {
		return nil
	}
	out := new(PortConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusReportingTaskStatus) DeepCopyInto(out *PrometheusReportingTaskStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusReportingTaskStatus.
func (in *PrometheusReportingTaskStatus) DeepCopy() *PrometheusReportingTaskStatus {
	if in == nil {
		return nil
	}
	out := new(PrometheusReportingTaskStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReadOnlyConfig) DeepCopyInto(out *ReadOnlyConfig) {
	*out = *in
	if in.MaximumTimerDrivenThreadCount != nil {
		in, out := &in.MaximumTimerDrivenThreadCount, &out.MaximumTimerDrivenThreadCount
		*out = new(int32)
		**out = **in
	}
	if in.MaximumEventDrivenThreadCount != nil {
		in, out := &in.MaximumEventDrivenThreadCount, &out.MaximumEventDrivenThreadCount
		*out = new(int32)
		**out = **in
	}
	if in.AdditionalSharedEnvs != nil {
		in, out := &in.AdditionalSharedEnvs, &out.AdditionalSharedEnvs
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.NifiProperties.DeepCopyInto(&out.NifiProperties)
	in.ZookeeperProperties.DeepCopyInto(&out.ZookeeperProperties)
	in.BootstrapProperties.DeepCopyInto(&out.BootstrapProperties)
	in.LogbackConfig.DeepCopyInto(&out.LogbackConfig)
	in.AuthorizerConfig.DeepCopyInto(&out.AuthorizerConfig)
	in.BootstrapNotificationServicesReplaceConfig.DeepCopyInto(&out.BootstrapNotificationServicesReplaceConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReadOnlyConfig.
func (in *ReadOnlyConfig) DeepCopy() *ReadOnlyConfig {
	if in == nil {
		return nil
	}
	out := new(ReadOnlyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryClientReference) DeepCopyInto(out *RegistryClientReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryClientReference.
func (in *RegistryClientReference) DeepCopy() *RegistryClientReference {
	if in == nil {
		return nil
	}
	out := new(RegistryClientReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollingUpgradeStatus) DeepCopyInto(out *RollingUpgradeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RollingUpgradeStatus.
func (in *RollingUpgradeStatus) DeepCopy() *RollingUpgradeStatus {
	if in == nil {
		return nil
	}
	out := new(RollingUpgradeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSLSecrets) DeepCopyInto(out *SSLSecrets) {
	*out = *in
	if in.IssuerRef != nil {
		in, out := &in.IssuerRef, &out.IssuerRef
		*out = new(metav1.ObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSLSecrets.
func (in *SSLSecrets) DeepCopy() *SSLSecrets {
	if in == nil {
		return nil
	}
	out := new(SSLSecrets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretConfigReference) DeepCopyInto(out *SecretConfigReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretConfigReference.
func (in *SecretConfigReference) DeepCopy() *SecretConfigReference {
	if in == nil {
		return nil
	}
	out := new(SecretConfigReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServicePolicy) DeepCopyInto(out *ServicePolicy) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServicePolicy.
func (in *ServicePolicy) DeepCopy() *ServicePolicy {
	if in == nil {
		return nil
	}
	out := new(ServicePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SingleUserConfiguration) DeepCopyInto(out *SingleUserConfiguration) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(SecretReference)
		**out = **in
	}
	out.SecretKeys = in.SecretKeys
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SingleUserConfiguration.
func (in *SingleUserConfiguration) DeepCopy() *SingleUserConfiguration {
	if in == nil {
		return nil
	}
	out := new(SingleUserConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageConfig) DeepCopyInto(out *StorageConfig) {
	*out = *in
	in.Metadata.DeepCopyInto(&out.Metadata)
	if in.PVCSpec != nil {
		in, out := &in.PVCSpec, &out.PVCSpec
		*out = new(corev1.PersistentVolumeClaimSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageConfig.
func (in *StorageConfig) DeepCopy() *StorageConfig {
	if in == nil {
		return nil
	}
	out := new(StorageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpdateRequest) DeepCopyInto(out *UpdateRequest) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpdateRequest.
func (in *UpdateRequest) DeepCopy() *UpdateRequest {
	if in == nil {
		return nil
	}
	out := new(UpdateRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserReference) DeepCopyInto(out *UserReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserReference.
func (in *UserReference) DeepCopy() *UserReference {
	if in == nil {
		return nil
	}
	out := new(UserReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserSecretKeys) DeepCopyInto(out *UserSecretKeys) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserSecretKeys.
func (in *UserSecretKeys) DeepCopy() *UserSecretKeys {
	if in == nil {
		return nil
	}
	out := new(UserSecretKeys)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeConfig) DeepCopyInto(out *VolumeConfig) {
	*out = *in
	in.VolumeMount.DeepCopyInto(&out.VolumeMount)
	in.VolumeSource.DeepCopyInto(&out.VolumeSource)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeConfig.
func (in *VolumeConfig) DeepCopy() *VolumeConfig {
	if in == nil {
		return nil
	}
	out := new(VolumeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZookeeperProperties) DeepCopyInto(out *ZookeeperProperties) {
	*out = *in
	if in.OverrideConfigMap != nil {
		in, out := &in.OverrideConfigMap, &out.OverrideConfigMap
		*out = new(ConfigmapReference)
		**out = **in
	}
	if in.OverrideSecretConfig != nil {
		in, out := &in.OverrideSecretConfig, &out.OverrideSecretConfig
		*out = new(SecretConfigReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZookeeperProperties.
func (in *ZookeeperProperties) DeepCopy() *ZookeeperProperties {
	if in == nil {
		return nil
	}
	out := new(ZookeeperProperties)
	in.DeepCopyInto(out)
	return out
}
