package nifi

import (
	"encoding/json"
	"fmt"
	"sort"

	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/util/strategicpatch"

	"github.com/konpyutaika/nifikop/pkg/util"
	nifiutil "github.com/konpyutaika/nifikop/pkg/util/nifi"
)

// applyPodOverrides merges a user supplied PodTemplateSpec onto the pod generated by the operator.
//
// The override is applied as a Kubernetes strategic merge patch: objects merge recursively, lists that
// carry a patchMergeKey (containers/initContainers/volumes by name, env by name, ports by containerPort,
// volumeMounts by mountPath, ...) merge by that key, and lists without one (tolerations, command, args,
// ...) are replaced. Only labels and annotations are taken from the override's metadata: the pod's
// identity (name, namespace, owner references) is owned by the operator, as are the labels the operator
// selects pods by, the hostname, the subdomain and the restartPolicy; those are restored after the merge.
//
// A nil override returns the input pod untouched. Neither argument is mutated.
func applyPodOverrides(pod *corev1.Pod, overrides *corev1.PodTemplateSpec) (*corev1.Pod, error) {
	if overrides == nil {
		return pod, nil
	}
	if err := validatePodOverrides(overrides); err != nil {
		return nil, err
	}

	original, err := json.Marshal(pod)
	if err != nil {
		return nil, fmt.Errorf("could not marshal generated pod: %w", err)
	}
	patch, err := marshalPatch(&corev1.Pod{
		ObjectMeta: metav1.ObjectMeta{
			Labels:      overrides.Labels,
			Annotations: overrides.Annotations,
		},
		Spec: overrides.Spec,
	})
	if err != nil {
		return nil, fmt.Errorf("could not marshal podOverrides: %w", err)
	}

	merged, err := strategicpatch.StrategicMergePatch(original, patch, corev1.Pod{})
	if err != nil {
		return nil, fmt.Errorf("could not apply podOverrides to generated pod: %w", err)
	}

	result := &corev1.Pod{}
	if err := json.Unmarshal(merged, result); err != nil {
		return nil, fmt.Errorf("could not decode pod after applying podOverrides: %w", err)
	}

	// Labels and annotations were merged into the JSON above; rebuild them through the same helpers the
	// rest of the operator uses so precedence (override wins) is explicit and nil maps stay nil. The labels
	// the operator lists and selects pods by are restored: overriding them would orphan the pod and make
	// the reconciler create a new one on every pass.
	if len(overrides.Labels) > 0 {
		result.Labels = util.MergeLabels(pod.Labels, overrides.Labels)
		for _, key := range operatorOwnedLabels() {
			if value, ok := pod.Labels[key]; ok {
				result.Labels[key] = value
			} else {
				delete(result.Labels, key)
			}
		}
	}
	if len(overrides.Annotations) > 0 {
		result.Annotations = util.MergeAnnotations(pod.Annotations, overrides.Annotations)
	}

	// A strategic merge patch places items that only exist in the patch before the original items. Keep
	// the operator's order (the "nifi" container stays first, env vars keep their $(VAR) dependency order)
	// and append user-added items after it.
	result.Spec.InitContainers = reorderContainers(pod.Spec.InitContainers, result.Spec.InitContainers)
	result.Spec.Containers = reorderContainers(pod.Spec.Containers, result.Spec.Containers)
	result.Spec.Volumes = reorderByKey(pod.Spec.Volumes, result.Spec.Volumes, func(v corev1.Volume) string { return v.Name })

	// Operator-owned fields: the headless service discovery and the node lifecycle depend on them.
	result.Spec.Hostname = pod.Spec.Hostname
	result.Spec.Subdomain = pod.Spec.Subdomain
	result.Spec.RestartPolicy = pod.Spec.RestartPolicy

	return result, nil
}

// operatorOwnedLabels lists the pod labels the reconciler keys on (pod lookup, node status, scale down).
func operatorOwnedLabels() []string {
	keys := []string{"nodeId"}
	for k := range nifiutil.LabelsForNifi("") {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func reorderContainers(original, merged []corev1.Container) []corev1.Container {
	byName := make(map[string]corev1.Container, len(original))
	for _, c := range original {
		byName[c.Name] = c
	}
	merged = reorderByKey(original, merged, func(c corev1.Container) string { return c.Name })
	for i := range merged {
		if orig, ok := byName[merged[i].Name]; ok {
			merged[i].Env = reorderByKey(orig.Env, merged[i].Env, func(e corev1.EnvVar) string { return e.Name })
		}
	}
	return merged
}

// reorderByKey stable-sorts merged so items also present in original keep original's order and items new
// in merged follow them, in their own order.
func reorderByKey[T any](original, merged []T, key func(T) string) []T {
	rank := make(map[string]int, len(original))
	for i, item := range original {
		rank[key(item)] = i
	}
	sort.SliceStable(merged, func(i, j int) bool {
		ri, iOk := rank[key(merged[i])]
		rj, jOk := rank[key(merged[j])]
		switch {
		case iOk && jOk:
			return ri < rj
		case iOk:
			return true
		default:
			return false
		}
	})
	return merged
}

// marshalPatch serializes the override as a strategic merge patch. Fields the user did not set are nil in
// the typed struct and would serialize as JSON null, which a strategic merge patch interprets as "delete
// this field" (PodSpec.containers has no omitempty, for instance). Nulls are stripped so an unset field
// is a no-op instead.
func marshalPatch(obj interface{}) ([]byte, error) {
	raw, err := json.Marshal(obj)
	if err != nil {
		return nil, err
	}
	var generic interface{}
	if err := json.Unmarshal(raw, &generic); err != nil {
		return nil, err
	}
	return json.Marshal(stripNulls(generic))
}

func stripNulls(v interface{}) interface{} {
	switch t := v.(type) {
	case map[string]interface{}:
		for k, val := range t {
			if val == nil {
				delete(t, k)
				continue
			}
			t[k] = stripNulls(val)
		}
		return t
	case []interface{}:
		for i, val := range t {
			t[i] = stripNulls(val)
		}
		return t
	default:
		return v
	}
}

// validatePodOverrides rejects list entries a strategic merge patch cannot key, and duplicate keys, which
// the patch would silently collapse into one entry.
func validatePodOverrides(overrides *corev1.PodTemplateSpec) error {
	if err := validateNames("podOverrides.spec.initContainers", overrides.Spec.InitContainers, func(c corev1.Container) string { return c.Name }); err != nil {
		return err
	}
	if err := validateNames("podOverrides.spec.containers", overrides.Spec.Containers, func(c corev1.Container) string { return c.Name }); err != nil {
		return err
	}
	return validateNames("podOverrides.spec.volumes", overrides.Spec.Volumes, func(v corev1.Volume) string { return v.Name })
}

func validateNames[T any](field string, items []T, name func(T) string) error {
	seen := make(map[string]int, len(items))
	for i, item := range items {
		n := name(item)
		if n == "" {
			return fmt.Errorf("%s[%d]: name is required", field, i)
		}
		if first, dup := seen[n]; dup {
			return fmt.Errorf("%s[%d]: name %q is already used by %s[%d]", field, i, n, field, first)
		}
		seen[n] = i
	}
	return nil
}
