name: Support Question
description: Any support questions you might have.
labels: ["support", "community"]
body:

  - type: markdown
    attributes:
      value: |
        Thanks for filing an issue! Before hitting submit, please answer the following questions.

        Fill in as much of the template below as you can. If you leave out information, we can't help you as well.

        We will try our best to answer the question, but we also have a mailing list and slack channel for any other questions.

  - type: dropdown
    attributes:
      label: Type of question
      options:
        - Best Practices
        - Implementation Assistance
        - General Context
    validations:
      required: true

  - type: textarea
    attributes:
      label: Support question
      description: Add any other context about the problem here
    validations:
      required: true

  - type: input
    attributes:
      label: NiFiKop version
      description: NiFiKop release or git SHA
      placeholder: v1.1..0-release

  - type: input
    attributes:
      label: Golang version
      description: Insert the output of `go version` here
      placeholder: go version go1.19 darwin/amd64

  - type: textarea
    attributes:
      label: Kubernetes version
      description: Insert the output of `kubectl version` here
      placeholder: |
        Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"darwin/amd64"}
        Kustomize Version: v4.5.7
        Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-08-11T22:48:42Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/arm64"}

  - type: input
    attributes:
      label: NiFi version
      description: Insert release NiFi version here
      placeholder: 1.17.0
