kind: Secret
apiVersion: v1
metadata:
  name: single-user-credentials
  namespace: nifikop
type: Opaque
stringData:
  username: nifikop
  password: nifikopnifikopnifikop
---
apiVersion: nifi.konpyutaika.com/v1
kind: NifiCluster
metadata:
  name: nifikop
  namespace: nifikop
spec:
  clusterImage: apache/nifi:2.5.0
  nodeUserIdentityTemplate: node-%d-nifikop
  singleUserConfiguration:
    enabled: true
    authorizerEnabled: true
    secretRef:
      name: "single-user-credentials"
      namespace: "nifikop"
    secretKeys:
      username: "username"
      password: "password"
  externalServices:
    - name: nifikop
      spec:
        portConfigs:
          - internalListenerName: https
            port: 443
          - internalListenerName: s2s
            port: 10000
        type: LoadBalancer
  listenersConfig:
    internalListeners:
      - containerPort: 8443
        name: https
        type: https
      - containerPort: 6007
        name: cluster
        type: cluster
      - containerPort: 10000
        name: s2s
        type: s2s
    sslSecrets:
      create: true
      tlsSecretName: nifikop-tls
  nifiClusterTaskSpec:
    retryDurationMinutes: 10
  nodeConfigGroups:
    default_group:
      fsGroup: 1337
      isNode: true
      resourcesRequirements:
        limits:
          cpu: "4"
          memory: 3Gi
        requests:
          cpu: "4"
          memory: 2Gi
      serviceAccountName: nifikop-cluster
      storageConfigs:
        - mountPath: /opt/nifi/nifi-current/logs
          name: logs
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
        - mountPath: /opt/nifi/data
          name: data
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
        - mountPath: /opt/nifi/flowfile_repository
          name: flowfile-repository
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
        - mountPath: /opt/nifi/nifi-current/conf
          name: conf
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
        - mountPath: /opt/nifi/content_repository
          name: content-repository-default
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
        - mountPath: /opt/nifi/provenance_repository
          name: provenance-repository-default
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
        - mountPath: /opt/nifi/extensions
          name: extensions-repository
          pvcSpec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
  nodes:
    - id: 0
      labels:
        nifi_cr: nifikop
        nifi_node_group: default_group
      nodeConfigGroup: default_group
  propagateLabels: false
  readOnlyConfig:
    bootstrapProperties:
      nifiJvmMemory: 3g
      overrideConfigs: |
        # Java 8 Tuning see https://community.hortonworks.com/articles/7882/hdfnifi-best-practices-for-setting-up-a-high-perfo.html for references
        java.arg.7=-XX:ReservedCodeCacheSize=256m
        java.arg.8=-XX:+UseCodeCacheFlushing
    maximumTimerDrivenThreadCount: 40
    nifiProperties:
      overrideConfigs: |
        nifi.nar.library.autoload.directory=../extensions
        nifi.sensitive.props.key=nifikopnifikopnifikop
      webProxyHosts:
        - nifikop.127.0.0.1.nip.io:443
        - nifikop.127.0.0.1.nip.io
  service:
    headlessEnabled: true
  sidecarConfigs:
    - args:
        - tail
        - -n+1
        - -F
        - /var/log/nifi-app.log
      image: busybox:1.36
      name: app-log
      resources:
        limits:
          cpu: 50m
          memory: 50Mi
        requests:
          cpu: 50m
          memory: 50Mi
      volumeMounts:
        - mountPath: /var/log
          name: logs
    - args:
        - tail
        - -n+1
        - -F
        - /var/log/nifi-bootstrap.log
      image: busybox:1.36
      name: bootstrap-log
      resources:
        limits:
          cpu: 50m
          memory: 50Mi
        requests:
          cpu: 50m
          memory: 50Mi
      volumeMounts:
        - mountPath: /var/log
          name: logs
    - args:
        - tail
        - -n+1
        - -F
        - /var/log/nifi-user.log
      image: busybox:1.36
      name: user-log
      resources:
        limits:
          cpu: 50m
          memory: 50Mi
        requests:
          cpu: 50m
          memory: 50Mi
      volumeMounts:
        - mountPath: /var/log
          name: logs
  clusterManager: kubernetes
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nifikop
  namespace: nifikop
  annotations:
    nginx.org/ssl-services: nifikop
    nginx.org/lb-method: ip_hash
spec:
  rules:
    - host: nifikop.127.0.0.1.nip.io
      http:
        paths:
          - backend:
              service:
                name: nifikop
                port:
                  number: 443
            path: /
            pathType: Prefix
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nifikop-cluster
  namespace: nifikop
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nifikop-cluster
  namespace: nifikop
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nifikop-cluster
  namespace: nifikop
subjects:
  - kind: ServiceAccount
    name: nifikop-cluster
    namespace: nifikop
roleRef:
  kind: Role
  name: nifikop-cluster
  apiGroup: rbac.authorization.k8s.io
