//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2020.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1 "github.com/konpyutaika/nifikop/api/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NifiNodeGroupAutoscaler) DeepCopyInto(out *NifiNodeGroupAutoscaler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NifiNodeGroupAutoscaler.
func (in *NifiNodeGroupAutoscaler) DeepCopy() *NifiNodeGroupAutoscaler {
	if in == nil {
		return nil
	}
	out := new(NifiNodeGroupAutoscaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NifiNodeGroupAutoscaler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NifiNodeGroupAutoscalerList) DeepCopyInto(out *NifiNodeGroupAutoscalerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NifiNodeGroupAutoscaler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NifiNodeGroupAutoscalerList.
func (in *NifiNodeGroupAutoscalerList) DeepCopy() *NifiNodeGroupAutoscalerList {
	if in == nil {
		return nil
	}
	out := new(NifiNodeGroupAutoscalerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NifiNodeGroupAutoscalerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NifiNodeGroupAutoscalerSpec) DeepCopyInto(out *NifiNodeGroupAutoscalerSpec) {
	*out = *in
	out.ClusterRef = in.ClusterRef
	if in.NodeLabelsSelector != nil {
		in, out := &in.NodeLabelsSelector, &out.NodeLabelsSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ReadOnlyConfig != nil {
		in, out := &in.ReadOnlyConfig, &out.ReadOnlyConfig
		*out = new(apiv1.ReadOnlyConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeConfig != nil {
		in, out := &in.NodeConfig, &out.NodeConfig
		*out = new(apiv1.NodeConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NifiNodeGroupAutoscalerSpec.
func (in *NifiNodeGroupAutoscalerSpec) DeepCopy() *NifiNodeGroupAutoscalerSpec {
	if in == nil {
		return nil
	}
	out := new(NifiNodeGroupAutoscalerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NifiNodeGroupAutoscalerStatus) DeepCopyInto(out *NifiNodeGroupAutoscalerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NifiNodeGroupAutoscalerStatus.
func (in *NifiNodeGroupAutoscalerStatus) DeepCopy() *NifiNodeGroupAutoscalerStatus {
	if in == nil {
		return nil
	}
	out := new(NifiNodeGroupAutoscalerStatus)
	in.DeepCopyInto(out)
	return out
}
