apiVersion: v2
name: nifi-cluster
description: A Helm chart for deploying NiFi clusters in Kubernetes
home: https://github.com/konpyutaika/nifikop
sources:
  - https://github.com/konpyutaika/nifikop
icon: https://konpyutaika.github.io/nifikop/img/nifikop.png
keywords:
  - nifi
  - nifikop
  - data
  - nifi-cluster

dependencies:
    - name: zookeeper
      version: 12.4.0
      repository: https://charts.bitnami.com/bitnami
      condition: zookeeper.enabled

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.14.2

# This is the NiFi version to be deployed
appVersion: "1.28.0"
