{{- if and .Values.rbacEnable (or (eq (include "nifikop.openshift.scc.create" .) "true") .Values.openshift.scc.existingName) }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: {{ template "nifikop.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    {{- include "userdefined.labels" . }}
  annotations:
    {{- include "userdefined.annotations" . }}
  name: system:openshift:scc:{{ include "nifikop.openshift.scc.name" . }}
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - {{ include "nifikop.openshift.scc.name" . }}
  resources:
  - securitycontextconstraints
  verbs:
  - use
{{- end }}
