apiVersion: nifi.konpyutaika.com/v1
kind: NifiCluster
metadata:
  name: {{ include "nifi-cluster.fullname" . }}
  labels:
    {{- include "nifi-cluster.labels" . | nindent 4 }}
spec:
  {{- if .Values.cluster.clientType }}
  clientType: {{ .Values.cluster.clientType }}
  {{- end }}
  {{- if .Values.cluster.type }}
  type: {{ .Values.cluster.type }}
  {{- end }}
  service:
    headlessEnabled: {{ .Values.cluster.service.headlessEnabled }}
    annotations:
    {{- toYaml .Values.cluster.service.annotations | nindent 6 }}
    labels:
    {{- toYaml .Values.cluster.service.labels | nindent 6 }}
  pod:
  {{- if .Values.cluster.pod.annotations }}
    annotations:
    {{- toYaml .Values.cluster.pod.annotations | nindent 6}}
  {{- end }}
  {{- if .Values.cluster.pod.labels }}
    labels:
    {{- toYaml .Values.cluster.pod.labels | nindent 6}}
  {{- end }}
  {{- if .Values.cluster.pod.hostAliases }}
    hostAliases:
    {{- toYaml .Values.cluster.pod.hostAliases | nindent 6}}
  {{- end }}
  {{- if .Values.cluster.pod.livenessProbe }}
    livenessProbe:
    {{- toYaml .Values.cluster.pod.livenessProbe | nindent 6}}
  {{- end -}}
  {{- if .Values.cluster.pod.readinessProbe }}
    readinessProbe:
    {{- toYaml .Values.cluster.pod.readinessProbe | nindent 6}}
  {{- end }}
  singleUserConfiguration:
    {{- if .Values.cluster.singleUserConfiguration.enabled }}
    enabled: {{ .Values.cluster.singleUserConfiguration.enabled }}
    {{- end }}
    {{- if .Values.cluster.singleUserConfiguration.secretRef }}
    secretRef:
    {{- toYaml .Values.cluster.singleUserConfiguration.secretRef | nindent 6 }}
    {{- end }}
    {{- if .Values.cluster.singleUserConfiguration.secretKeys }}
    secretKeys:
    {{- toYaml .Values.cluster.singleUserConfiguration.secretKeys | nindent 6 }}
    {{- end }}
    {{- if .Values.cluster.singleUserConfiguration.authorizerEnabled }}
    authorizerEnabled: {{ .Values.cluster.singleUserConfiguration.authorizerEnabled }}
    {{- end }}
  {{- if .Values.cluster.manager }}
  clusterManager: {{ .Values.cluster.manager }}
  {{- end }}
  {{- if ne .Values.cluster.manager "kubernetes" }}
  zkAddress: {{ .Values.cluster.zkAddress }}
  zkPath: {{ .Values.cluster.zkPath }}
  {{- end }}
  clusterImage: "{{ .Values.cluster.image.repository }}:{{ default .Chart.AppVersion .Values.cluster.image.tag }}"
  initContainerImage: "{{ .Values.cluster.initContainerImage.repository }}:{{ .Values.cluster.initContainerImage.tag }}"
{{- if .Values.cluster.oneNifiNodePerNode }}
  oneNifiNodePerNode: {{ .Values.cluster.oneNifiNodePerNode }}
{{- end }}
{{- if .Values.cluster.initContainers }}
  initContainers:
  {{- toYaml .Values.cluster.initContainers | nindent 4 }}
{{- end }}
{{- if .Values.cluster.sidecarConfigs }}
  sidecarConfigs:
  {{- toYaml .Values.cluster.sidecarConfigs | nindent 4 }}
{{- end }}
{{- if .Values.cluster.nodeUserIdentityTemplate }}
  nodeUserIdentityTemplate: {{ .Values.cluster.nodeUserIdentityTemplate }}
{{- end }}
{{- if .Values.cluster.nifiControllerTemplate }}
  nifiControllerTemplate: {{ .Values.cluster.nifiControllerTemplate }}
{{- end }}
{{- if .Values.cluster.controllerUserIdentity }}
  controllerUserIdentity: {{ .Values.cluster.controllerUserIdentity }}
{{- end }}
{{- if .Values.cluster.managedAdminUsers }}
  managedAdminUsers:
  {{- toYaml .Values.cluster.managedAdminUsers | nindent 4 }}
{{- end }}
{{- if .Values.cluster.managedReaderUsers }}
  managedReaderUsers:
  {{- toYaml .Values.cluster.managedReaderUsers | nindent 4 }}
{{- end }}
  disruptionBudget:
  {{- toYaml .Values.cluster.disruptionBudget | nindent 4 }}
{{- if .Values.cluster.topologySpreadConstraints }}
  topologySpreadConstraints:
  {{- toYaml .Values.cluster.topologySpreadConstraints | nindent 4 }}
{{- end }}
  ldapConfiguration:
  {{- toYaml .Values.cluster.ldapConfiguration | nindent 4 }}
  readOnlyConfig:
{{- if .Values.cluster.maximumTimerDrivenThreadCount }}
    maximumTimerDrivenThreadCount: {{ .Values.cluster.maximumTimerDrivenThreadCount }}
{{- end }}
{{- if .Values.cluster.additionalSharedEnvs }}
    additionalSharedEnvs:
    {{- toYaml .Values.cluster.additionalSharedEnvs | nindent 6 }}
{{- end }}
    logbackConfig:
    {{- if .Values.cluster.logbackConfig.replaceSecretConfig }}
      replaceSecretConfig:
        data: {{ .Values.cluster.logbackConfig.replaceSecretConfig.data }}
        name: {{ .Values.cluster.logbackConfig.replaceSecretConfig.name }}
        namespace: {{ default .Release.Namespace .Values.cluster.logbackConfig.replaceSecretConfig.namespace }}
    {{- else }}
      # the default
      replaceSecretConfig:
        data: logback.xml
        name: {{ include "nifi-cluster.fullname" . }}
        namespace: {{ .Release.Namespace }}
    {{- end }}
    {{- if .Values.cluster.logbackConfig.replaceConfigMap }}
      replaceConfigMap:
        data: {{ .Values.cluster.logbackConfig.replaceConfigMap.data }}
        name: {{ .Values.cluster.logbackConfig.replaceConfigMap.name }}
        namespace: {{ default .Release.Namespace .Values.cluster.logbackConfig.replaceConfigMap.namespace }}
    {{- end }}
    nifiProperties:
    {{- if .Values.cluster.nifiProperties.overrideSecretConfig }}
      overrideSecretConfig:
        data: {{ .Values.cluster.nifiProperties.overrideSecretConfig.data }}
        name: {{ .Values.cluster.nifiProperties.overrideSecretConfig.name }}
        namespace: {{ default .Release.Namespace .Values.cluster.nifiProperties.overrideSecretConfig.namespace }}
    {{- else }}
      # the default
      overrideSecretConfig:
        data: nifi.properties
        name: {{ include "nifi-cluster.fullname" . }}
        namespace: {{ .Release.Namespace }}
    {{- end }}
    {{- if .Values.cluster.nifiProperties.overrideConfigMap }}
      overrideConfigMap:
        data: {{ .Values.cluster.nifiProperties.overrideConfigMap.data }}
        name: {{ .Values.cluster.nifiProperties.overrideConfigMap.name }}
        namespace: {{ default .Release.Namespace .Values.cluster.nifiProperties.overrideConfigMap.namespace }}
    {{- end }}
      webProxyHosts:
      {{- toYaml .Values.cluster.nifiProperties.webProxyHosts | nindent 8}}
      {{- if and .Values.cluster.nifiProperties.webProxyNodePorts.enabled .Values.cluster.externalServices }}
      {{- range $externalSvc := .Values.cluster.externalServices }}
      {{- if eq $externalSvc.spec.type "NodePort" }}
      {{- range $portConfig := $externalSvc.spec.portConfigs }}
      {{- range $nodePortHost := $.Values.cluster.nifiProperties.webProxyNodePorts.hosts }}
      {{- printf "- %s:%s" $nodePortHost (toString $portConfig.nodePort) | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- if .Values.cluster.nifiProperties.needClientAuth }}
      needClientAuth: {{ .Values.cluster.nifiProperties.needClientAuth }}
      {{- end }}
    zookeeperProperties:
      overrideSecretConfig:
        data: zookeeper.properties
        name: {{ include "nifi-cluster.fullname" . }}
        namespace: {{ .Release.Namespace }}
    bootstrapProperties:
      overrideSecretConfig:
        data: bootstrap.conf
        name: {{ include "nifi-cluster.fullname" . }}
        namespace: {{ .Release.Namespace }}
      nifiJvmMemory: {{ .Values.cluster.bootstrapProperties.nifiJvmMemory }}
  nodeConfigGroups:
  {{- if empty .Values.cluster.nodeConfigGroups }}
    {{- if eq .Values.cluster.manager "kubernetes" }}
    default-group:
      serviceAccountName: {{ tpl (default (include "nifi-cluster.fullname" .) .Values.serviceAccount.name) . }}
    {{- end }}
  {{- else }}
  {{- tpl (toYaml .Values.cluster.nodeConfigGroups) . | nindent 4 }}
  {{- end }}
  nodes:
  {{- toYaml .Values.cluster.nodes | nindent 4 }}
  propagateLabels: {{ .Values.cluster.propagateLabels }}
  nifiClusterTaskSpec:
    retryDurationMinutes: {{ .Values.cluster.retryDurationMinutes }}
  listenersConfig:
  {{- toYaml .Values.cluster.listenersConfig | nindent 4 }}
  externalServices:
  {{- toYaml .Values.cluster.externalServices | nindent 4 }}
