{{- if eq .Values.cluster.manager "kubernetes" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ tpl (default (include "nifi-cluster.fullname" .) .Values.cluster.managerServiceAccount.name) . }}
  namespace: {{ .Release.Namespace }}
  annotations: 
{{ toYaml .Values.cluster.managerServiceAccount.annotations | indent 4 }}
  labels: 
{{ toYaml .Values.cluster.managerServiceAccount.labels | indent 4 }}
{{- end }}

